Numpy

Numpy

In [3]:
import numpy as np # Used to import numpy as np to use its functions

In [16]:
nums = list(range(1, 25)) # Used to create a list
print("List : ", nums)
array = np.array(nums)
print(f"Array : {array}")
type(array)

List :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


numpy.ndarray

In [12]:
arr = np.array([1,2,3,4,5]) # Used to create a array
print(arr)

[1 2 3 4 5]


In [17]:
arr = np.arange(1, 25) # Used to create a array with the given range
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [50]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]]) # Used to create a 2D array
arr3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]]) # Used to create 3D array
print(arr2.ndim) # Used to find the dimension of the array
print(arr3.ndim)
print(arr2)

2
3
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
# Creating a 3d Array (2 blocks, 3 rows, 4 columns)
arr = np.array([[[1,2,3,4], [5,6,7,8], [17,18,19,20]], [[9,10,11,12], [13,14,15,16], [21,22,23,24]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [13 14 15 16]
  [21 22 23 24]]]
3


In [31]:
arr4 = np.zeros((2,3)) # Used to create a 2D array with zeros
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [51]:
arr5 = np.linspace(1, 10, 5) # Used to create a array with the given range
arr6 = np.linspace(1,10,8).reshape(2,2,2) # Used to create a array with the given range in 3D array 
arr7 = np.linspace(1,10,4).reshape(2,2) # Used to create a array with the given range in 2D array
print("Dimension of arr6 : ",arr6.ndim)
print("Dimension of arr5 : ",arr5.ndim)
print("Dimension of arr7 : ",arr7.ndim)

Dimension of arr6 :  3
Dimension of arr5 :  1
Dimension of arr7 :  2


In [61]:
nums1 = np.arange(1,31).reshape(5,6) # Used to create a array with the given range and resape it in 5x6 matrix
print(nums1)
print(nums1.shape)  # Used to find the shape of the array
print(nums1.size) # Used to find the size of the array
print(nums1.dtype) # Used to find the data type of the array
print(nums1.T) # Used to transpose the array
print(nums1.ravel()) # Used to flatten the array
print(nums1.max()) # Used to find the maximum value of the array
print(nums1.min()) # Used to find the minimum value of the array
print(nums1.sum()) # Used to find the sum of the array
print(nums1.mean()) # Used to find the mean of the array
print(nums1.std()) # Used to find the standard deviation of the array.
print(nums1.argsort()) # Used to find the index of the array

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)
30
int64
[[ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]
 [ 6 12 18 24 30]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
30
1
465
15.5
8.65544144839919
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [94]:
arr = np.random.randint(1, 100, 10) # Used to create a random array with the given range
print(arr, "\n")
arr1 = np.random.randint(1, 100, (3,4)) # Used to create a random 2D array with the given range
print(arr1, "\n")
arr2 = np.random.randint(1, 100, (3,3,3)) # Used to create a random 3D array with the given range
print(arr2, "\n")

[ 6 30  4 11 78 66 79 46 12 92] 

[[12 67 22 66]
 [20 11  3 61]
 [32 12 48 87]] 

[[[59 65 13]
  [13 55 30]
  [83 96 23]]

 [[ 2 32 60]
  [85 93 54]
  [67 67 24]]

 [[12 80 34]
  [43 79 40]
  [35 22  3]]] 



In [105]:
arr = np.random.random((10,5))
print(arr)

[[0.23841951 0.43469152 0.17905388 0.75306778 0.26198665]
 [0.90571847 0.50949135 0.35291755 0.97929257 0.12212215]
 [0.31153166 0.90309373 0.03639197 0.00308272 0.26026704]
 [0.89688618 0.56104909 0.06082778 0.68016865 0.67918693]
 [0.41190243 0.27318984 0.07174361 0.34202639 0.54568532]
 [0.16168816 0.38271409 0.30369469 0.9830108  0.28098407]
 [0.38886901 0.90455074 0.65909259 0.45059305 0.77524811]
 [0.44673278 0.486051   0.55825279 0.85538913 0.32964661]
 [0.01299633 0.51822677 0.12408214 0.79407249 0.77252203]
 [0.6560659  0.4971774  0.5384133  0.53678944 0.65958089]]
